### ISSUE TITLE
minor fixes for image builds

### ISSUE THREAD

**Issue by px3l** [binocarlos/boiler-stack#38]

**Comment by px3l** [comment]
Running `make frontend.build` throws errors:

```
ERROR in ./~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: Error: Cannot resolve 'file' or 'directory' /app/node_modules/react/lib/ViewportMetrics in /app/node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 27:22-58
```

Even after installing the module manually

**Comment by px3l** [comment]
`docker-compose up` throws 

```
boiler_router | 2016/11/19 15:59:03 [emerg] 10#10: host not found in upstream "api:80" in /etc/nginx/nginx.conf:29
boiler_router | nginx: [emerg] host not found in upstream "api:80" in /etc/nginx/nginx.conf:29
boiler_router exited with code 1
```

**Comment by binocarlos** [comment]
@px3l odd issue about the tap plugin - it's needed because mobile devices have latency for click events - see [this stackoverflow](http://stackoverflow.com/questions/40670018/error-in-react-tap-event-plugin-src-injecttapeventplugin-js) for a hack

**Comment by binocarlos** [comment]
@px3l for the `docker-compose up` error - I should have mentioned - try the `29-quote-page-experiment` branch:

```
$ git checkout 29-quote-page-experiment
```
